# Generated by Django 5.2.3 on 2025-07-26 11:10

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proof_of_life", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proofoflifesettings",
            name="minimum_confidence_score",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.80"),
                help_text="Minimum confidence score required for successful verification",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000")),
                    django.core.validators.MaxValueValidator(Decimal("1.000")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="proofoflifesettings",
            name="minimum_liveness_score",
            field=models.DecimalField(
                decimal_places=3,
                default=Decimal("0.70"),
                help_text="Minimum liveness score required for successful verification",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000")),
                    django.core.validators.MaxValueValidator(Decimal("1.000")),
                ],
            ),
        ),
    ]
