repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=88]

  # Ruff - Fast Python linter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: [--profile, black, --line-length, "88"]

  # Django-specific checks
  - repo: local
    hooks:
      - id: django-check
        name: Django Check
        entry: python manage.py check
        language: system
        types: [python]
        pass_filenames: false
        additional_dependencies: []
        args: ["--settings=core.settings.dev"]
        files: '\.py$'

  # Security checks with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.5
    hooks:
      - id: bandit
        args: ["-r", "apps/", "-f", "json", "-x", "*/tests/*,*/migrations/*"]
        pass_filenames: false

  # Pre-commit hooks for general files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: 'docker-compose.*\.yml$'
      - id: check-json
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-case-conflict

  # Type checking with mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.16.1
    hooks:
      - id: mypy
        additional_dependencies:
          - django-stubs
          - types-requests
          - python-dotenv
          - djangorestframework-stubs
          - djangorestframework
          - djangorestframework-simplejwt
          - django-cors-headers
          - drf-spectacular
          - django-debug-toolbar
          - psycopg[binary]
        args: [--ignore-missing-imports, --show-error-codes]
        files: '^(apps|core)/.*\.py$'
