# Generated by Django 5.2.3 on 2025-06-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verification_expires_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When face verification expires and user needs to re-verify",
                null=True,
            ),
        ),
    ]
