# Generated by Django 5.2.3 on 2025-06-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_verification_expires_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auth_faces_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of faces added during successful authentications (max 100)",
            ),
        ),
    ]
