# Generated by Django 5.2.3 on 2025-07-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_auth_faces_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.URLField(
                blank=True,
                help_text="URL to user's profile picture stored in Azure Blob Storage",
                max_length=500,
                null=True,
            ),
        ),
    ]
