# Generated by Django 5.2.3 on 2025-07-24 16:53

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_profile_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the OTP",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(help_text="6-digit OTP code", max_length=6)),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[("sms", "SMS"), ("email", "Email")],
                        help_text="Method used to deliver the OTP (SMS or Email)",
                        max_length=5,
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this OTP has been used for authentication",
                    ),
                ),
                (
                    "is_expired",
                    models.BooleanField(
                        default=False, help_text="Whether this OTP has expired"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the OTP was created",
                    ),
                ),
                ("expires_at", models.DateTimeField(help_text="When the OTP expires")),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, help_text="When the OTP was used", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User this OTP belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "db_table": "users_otp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "code"], name="users_otp_user_id_425c94_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="users_otp_created_907e74_idx"
                    ),
                    models.Index(
                        fields=["expires_at"], name="users_otp_expires_8f43b7_idx"
                    ),
                ],
            },
        ),
    ]
