# Generated by Django 5.2.3 on 2025-07-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="User's street address (optional)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                help_text="User's city (optional)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="User's country (optional)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="User's postal code (optional)",
                max_length=20,
                null=True,
            ),
        ),
    ]
